"""Build Apple's string tables from the reviewed Chinese / English / Japanese TSV sources."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ("zh-Hans", "en", "ja")


def read_rows(name):
    rows = []
    for line in (ROOT / "Localization" / name).read_text().splitlines():
        if not line.strip():
            continue
        columns = [value.replace(r"\n", "\n") for value in line.split("\t")]
        if len(columns) != 3 or not all(columns):
            raise ValueError(f"Invalid translation row: {line}")
        rows.append(columns)
    return rows


def write_table(path, entries):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("// Generated by scripts/build_localizations.py\n" + "".join(
        f"{json.dumps(key, ensure_ascii=False)} = {json.dumps(value, ensure_ascii=False)};\n"
        for key, value in entries.items()))


ui = read_rows("Interface.tsv")
assert len({row[0] for row in ui}) == len(ui)
singular = {
    "%ld天": "%ld day", "%ld岁": "%ld year", "度过%ld个周末": "Spend %ld weekend",
    "享受%ld个夏天": "Enjoy %ld summer", "吃%ld顿早餐": "Eat %ld breakfast",
    "读%ld本书": "Read %ld book", "回%ld次老家": "Visit your hometown %ld time",
    "呼吸，已留下%ld条线": "Breath, %ld trace left"
}
for index, language in enumerate(LANGUAGES):
    folder = ROOT / "App" / f"{language}.lproj"
    entries = {row[0]: row[index] for row in ui}
    if language == "en":
        entries.update({key + ".one": value for key, value in singular.items()})
    write_table(folder / "Localizable.strings", entries)
    write_table(folder / "InfoPlist.strings", {
        "CFBundleDisplayName": ("墨尔本草稿", "Melbourne Drafts", "メルボルン草稿")[index],
        "NSCameraUsageDescription": (
            "用于“没有拍下”的实时取景，不会拍摄或保存照片。",
            "Used for the live viewfinder in Not Taken. No photos are captured or saved.",
            "「撮らなかった」のリアルタイム表示に使用します。写真の撮影や保存は行いません。"
        )[index]
    })
    lexicon = {}
    for kind in ("verb", "adjective", "noun"):
        source = ROOT / "Localization" / f"{kind}.tsv"
        if source.exists():
            for row in read_rows(source.name):
                lexicon[kind + "." + row[0]] = row[index]
    write_table(folder / "Lexicon.strings", lexicon)
print(f"Generated {len(ui)} interface strings in three languages")
